{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
 name: {{ include "helm-node-sample-template.name" . }}
 namespace: dev-{{ .Values.prefix }}
spec:
 tls:
 - hosts:
   - dev-{{ .Values.prefix }}.{{ .Values.ingress.host}}
   secretName: {{ .Values.ingress.secret}}
 rules:
 - host: dev-{{ .Values.prefix }}.{{ .Values.ingress.host}}
   http:
     paths:
     - path: /
       backend:
         serviceName: {{ include "helm-node-sample-template.name" . }}
         servicePort: 80
{{- end }}